/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package view;

/**
 *
 * @author IFAM
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        vacinadoMenuItem = new javax.swing.JMenuItem();
        vacinaMenuItem = new javax.swing.JMenuItem();
        aplicarMenuItem = new javax.swing.JMenuItem();
        vacinadorMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Cadastro");

        vacinadoMenuItem.setMnemonic('o');
        vacinadoMenuItem.setText("Vacinado");
        vacinadoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vacinadoMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(vacinadoMenuItem);

        vacinaMenuItem.setMnemonic('s');
        vacinaMenuItem.setText("Vacina");
        vacinaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vacinaMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(vacinaMenuItem);

        aplicarMenuItem.setMnemonic('a');
        aplicarMenuItem.setText("Aplicar");
        fileMenu.add(aplicarMenuItem);

        vacinadorMenuItem.setMnemonic('x');
        vacinadorMenuItem.setText("Vacinador");
        vacinadorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vacinadorMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(vacinadorMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vacinadorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vacinadorMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_vacinadorMenuItemActionPerformed

    private void vacinaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vacinaMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vacinaMenuItemActionPerformed

    private void vacinadoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vacinadoMenuItemActionPerformed
        // TODO add your handling code here:
        ClienteView clienteView = new ClienteView();
        this.desktopPane.add(clienteView);
        clienteView.setVisible(true);
    }//GEN-LAST:event_vacinadoMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aplicarMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem vacinaMenuItem;
    private javax.swing.JMenuItem vacinadoMenuItem;
    private javax.swing.JMenuItem vacinadorMenuItem;
    // End of variables declaration//GEN-END:variables

}
